version: "3.5"
services:
  llm-chat-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_llm_chat_db:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_llm_chat_db:

