version: "3.5"
services:
  llm-chat-db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_llm_chat_db:/var/lib/postgresql/data
    restart: always

  llm-chat-api:
    build:
      context: .
      dockerfile: ./api.Dockerfile
    image: ghcr.io/ngyngcphu/llm-chat:latest
    container_name: llm-chat-api
    ports:
      - 8080:8080
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
    restart: always

  llm-chat-ui:
    build:
      context: .
      dockerfile: ./ui.Dockerfile
    image: ghcr.io/ngyngcphu/llm-chat:latest
    container_name: llm-chat-ui
    ports:
      - 3000:3000
    volumes:
      - .env:/app/.env
    restart: always
  
volumes:
  postgres_llm_chat_db:
